name: Publish Helm Chart

on:
  push:
    branches:
      - main

jobs:
  publish-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Package Helm chart
        run: |
          mkdir -p chart-package
          helm package charts/supabase --destination chart-package

      - name: Generate Helm chart index
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          # Extract the repository name from the full repo string "owner/repo"
          repo_name=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)
          echo "Using repository name: $repo_name"
          # Generate index.yaml with the correct URL (adjust if needed)
          helm repo index chart-package --url https://${GITHUB_REPOSITORY_OWNER}.github.io/${repo_name}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: chart-package 